version: '3.8'

services:
  etl:
    build: .
    image: etl-flight-project:latest
    container_name: etl-flight
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - OPENSKY_API_URL=${OPENSKY_API_URL}
      - DATABASE_PATH=/app/data/flights.db
      - ENABLE_GOOGLE_SHEETS_EXPORT=${ENABLE_GOOGLE_SHEETS_EXPORT}
    restart: unless-stopped
